### ISSUE TITLE
My Order Api Issue still not resolved

### ISSUE THREAD

**Issue by Rishabh31User** [Shopify/mobile-buy-sdk-android#293]
Hi ,
I having issue with My Order Api only for specific User ,otherwise for all user that Api responding well ,i am attaching screenshot what i getting after failure of MyOrder Api .please help
![screenshot_20160921-023928](https://cloud.githubusercontent.com/assets/15205021/18689263/df1b1a10-7fa5-11e6-9131-f81025e57710.png)

**Comment by henrytao-me** [comment]
Hi @Rishabh31User, can you provide more information about the context? How to reproduce it? Thanks.

**Comment by Rishabh31User** [comment]
Yes Scenario is like that when i am looged in with my id like(aarshi@mobikasa.com) then i can get all my orders from Shopify Api in my android App. but if i another account like(davidl@1800flowers.com) then i am getting this exception from API

**Comment by Rishabh31User** [comment]
Please update us for that

**Comment by krisorr** [comment]
Hi @Rishabh31User I will take a look

**Comment by Rishabh31User** [comment]
thanks a lot ....

**Comment by Rishabh31User** [comment]
any update for this

**Comment by krisorr** [comment]
Hi, still looking into it.  There may be a bug with the value parsing, will
let you know as soon as I verify.

**Comment by krisorr** [comment]
@Rishabh31User - PR #298 should fix this issue for you.  It is on the bug/293-line_item_property_parsing branch, which you are welcome to try out.  It is going into our next release which is targeted for later this week/early next week.

**Comment by Rishabh31User** [comment]
But issue is still there  ,,parsing exception is still showing.

**Comment by krisorr** [comment]
@Rishabh31User - the parsing issue is still occuring on the bug/293-line_item_property_parsing branch?
Please try the newest release, 2.0.2.

`compile 'com.shopify.mobilebuysdk:buy:2.0.2'`

**Comment by Rishabh31User** [comment]
You mean i  need to update my shpify sdk

**Comment by Rishabh31User** [comment]
i update the version of my  shopify sdk as u suggested compile 'com.shopify.mobilebuysdk:buy:2.0.2'
but still the exception persist

**Comment by Rishabh31User** [comment]
Actually i am not using dependency in my app ,we are download whole sdk from this link
https://github.com/Shopify/mobile-buy-sdk-android ,so as i am seeing on github only 2.0.1 sdk is available .can you please provide a link from where i can download 2.0.2 full sdk

**Comment by krisorr** [comment]
https://github.com/Shopify/mobile-buy-sdk-android/releases/tag/2.0.2

**Comment by Rishabh31User** [comment]
Thanx a lot its done ....appreciate your help sir

**Comment by krisorr** [comment]
No worries, glad I could help.
